Feature: TO DO

    Scenario: Create a dealer/organization that can be used to create a request.    

    Given current page is add organization
    When selects to create a dealer/organization  
    And selects a customer from the drop down option that is click enabled (Nisan as of now).
    And chooses Dealer as the org type
    And use billing address and inspection location as same by checking off the check box for 'same as billing address'.
    And click on 'Submit' button to create the organization
    Then add organization page is displayed




# CHECK
    Scenario: Import dealer request to check if pilot state is working

    Given  dealer request is imported and is in the body of the import
    And "state" mentioned as the pilot state matches the pilot states that are in the DB
    And after a successful submit, check the following folder path /mnt/sdrive/dataload/AIM/InspexDev/Nissan/requests/In. The file shouldn't be in the folder structure.
    4. Then search for the request id in CRM.
    5. The request should be auto scheduled.
    6. The request status should be automatically be at 'S' scheduled.
    7. Then using the app, check to see if the inspection shows up in the app.

    Inspection should display in the app.





    Scenario: Import dealer request and make sure it auto schedules.

        When dealer request is imported
        And if succesful a request id will be generated by postman
        And CRM is searched using that ID to see if the request has been scheduled automatically
        And the inspection of the request should be auto scheduled and the status of the request should update to 'Scheduled'      
        And log in to Aim Inspect app and see if the inspection shows up in the app
        Then inspection should show up in the app accordingly for the date it has been scheduled for.




    Scenario: Using the app, UTC a dealer request where a message is sent to scheduler 

        Given dealer request is imported using postman
        And request automatically at 'Scheduled' status and the appointment status should be scheduled as well
        When log in to Aim inspect app and UTC the inspection 
        And select reason as 'weather', 'Wrong location', 'Inspector time constraint', 'or 'vehicle unavailable' with sub reason as (missing keys, contact unavailable, cannot locate, Mechanical Issues)
        And come back to CRM and see if the appointment has been UTC'd
        Then UTC result displayed
    




    Scenario: Reschedule a dealer request by selecting the next earlist date available when an appointment has been UTC'd 

    Given dealer request is imported
    When go to CRM 
    And check to see if the request has been scheduled
    And go to Aim Inspect app 
    And UTC the inspection 
    And select 'vehicle unavailable' for reason 
    And select 'In body' for sub-reason).
    And come back to CRM
    And search for that request 
    And go appointment dialog box and view the UTC's inspection.
    And select a date from the date picker field to reschedule the appointment.
    And go to Aim inspect app on the date that the inspection has been scheduled for 
    Then see appropriate inspection shows up

    



    Scenario: Using the app, UTC a dealer request where the inspection gets cancelled 

    Given dealer request is imported using postman
    And the request should automatically be at 'Scheduled' status 
    And the appointment status should be scheduled as well
    When log in to Aim inspect app 
    And UTC the inspection 
    And select reason as 'Vehicle Already Picked Up', 'Vehicle Purchased/Sold', 'Previously inspected'.
    And come back to CRM 
    Then the appointment has been UTC'd

 





    Scenario: Using the App, UTC a dealer request where a messge is sent CSR queue for rescheduling

    When create a home request in CRM.
    And schedule an appointment.
    And the request status will automatically update to 'Scheduled' status and the appointment status should be scheduled as well.
    And log in to Aim inspect app 
    And UTC the inspection 
    And select reason as 'weather' or 'Missed Appointment with sub reason as (lessee cancel, No one at location, Could not find location)'
    Then come back to CRM 
    And the appointment has been UTC'd

    





    Scenario: Using the App, UTC a home request where a messge is sent CSR queue for rescheduling

    When Create a home request in CRM
    And schedule an appointment
    And the request status will automatically update to 'Scheduled' status
    And the appointment status should be scheduled as well
    And log in to Aim inspect app 
    And UTC the inspection 
    And select reason as 'weather' or 'Missed Appointment with sub reason as (lessee cancel, No one at location, Could not find location)'
    Then come back to CRM 
    And see appointment has been UTC'd

   




    Scenario: Using the App, UTC a home request where the appointment gets cancelled

    When create a home request in CRM
    And schedule an appointment
    And the request status will automatically update to 'Scheduled' status 
    And the appointment status should be scheduled as well
    And log in to Aim inspect app 
    And UTC the inspection 
    And select reason as 'Vehicle Purchased/Sold' or 'Extended Lease'
    Then come back to CRM 
    And see the appointment has been UTC'd

   




    Scenario: Successfully complete an inspection for home request and make sure it has a CR after completion of the inspection in CRM

    When create a home request 
    And schedule an inspection.
    And using Aim inspect app complete the inspection.
    And come back to CRM 
    And search for the request 
    Then see if inspection has a completed check mark 
    And a CR is displayed and viewable.

   




    Scenario: Successfully complete an inspection for dealer request and make sure it has a CR after completion of the inspection in CRM

    When create or import a dealer request 
    And schedule an inspection
    And using Aim inspect app complete the inspection
    And come back to CRM 
    And search for the request 
    Then see inspection has a completed check mark 
    And a CR is displayed and viewable.

    




    Scenario: Dealer request not matching up to home request properly

    Given dealer import does not have any lessee info

    When create  a home request 
    And keep a copy of lessee acct #
    And using the home request acct # set up a dealer request using postman
    And import a dealer request"
    Then  dealer request displayed
   




    Scenario: Import a dealer request when a home request exists 

    When create a home request in CRM
    And submit a dealer import using postman 
    And suse the same customer, account # and vin used to create a home request
    Then the home request should be cancelled and the dealer request should be created with an active appointment




    Scenario: Import a dealer request when a home request is active 

    When create a home request in CRM
    And schedule an appointment.
    And submit a dealer import using postman using the same customer, account # and vin used to create a home request
    Then the home request should be cancelled and the dealer request should be created with an active appointment





    Scenario: Import a dealer request when a home request is complete

    Given the dealer request has to come in before 58 days to associate it with the home request
    When create a home request
    And Schedule an appointment then complete it using the Aim inspect app
    And send a dealer import using postman for the same customer, account # and vin.
    Then the home request status should stay at completed.
    






    Scenario: Reschedule a home request that has been completed

    When create a home request
    And schedule an appointment and complete the inspection.
    And reschedule an appointment
    Then user should be able to reschedule an appointment





    Scenario: Dealer request Import

    When send a dealer request import via Postman
    Then if successful, postman should give 200 as the code and ID for the request that was created





    Scenario: Cancel Dealer request Import

    When send a cancel dealer request import via Postman
    Then if successful, postman should give 200 as the code and ID for the request should be the same





    Scenario: Cancel Dealer request Import customer with mix letter

    When send a cancel dealer request import via Postman where customer name is mixed with upper and lower case
    Then if successful, postman should give 200 as the code and ID for the request should be the same




    Scenario: Cancel Dealer request Import customer with upper case letters

    When send a cancel dealer request import via Postman where customer name is only Uppser case
    Then if successful, postman should give 200 as the code and ID for the request should be the same




    Scenario: ESB lease import 

    When send a lease import file through FTP /test/dev/nissan/inbox/ then wait for 30 secs
    And go to sdrive/dataload/AIM/InspexDev/Nissan_Lease_Load/In to see if a lease import fiel that you sent is in this folder
    And go to CRM and search for lessee(s) from the lease import file using lessee's name or VIN and or address
    Then User should be able to see the file under that folder
    And User should be able to find lessee's request using lessee's name or VIN and or adress



    TO DO
    Scenario: ESB lease import processing logic (Insert)

    Given Lease load file needs to be processed first
    When Grab/copy an account number from the lease load file that has 'A' to indicate it's an insert request data.
    And go to CRM and search for the reuqest using the account number by pasting the copied account number in the basic search field.
    Then if the request already exists in CRM then the system will do nothing.
    And if the request is not found then appropriate actions will happen




    Scenario: ESB lease import processing logic (Update)

    Given Lease load file processed first
    And grab/copy an account number from the lease load file that has 'C' to indicate it's an update request data.
    When go to CRM and search for the reuqest using the account number by pasting the copied account number in the basic search field.
    And look for a record that matches this customer, inspection type, VIN, and lease #
    Then appropriate response received





    Scenario: ESB lease import processing logic (Cancel)

    Given Lease load file processed first
    And Grab/copy an account number from the lease load file that has 'T' to indicate it's a cancelled request data.
    When Go to CRM and search for the reuqest using the account number by pasting the copied account number in the basic search field.
    Then Look for a record that matches this customer, inspection type, VIN, and lease #
    And appropriate response is received case 2





    Scenario: Test ESB Dealer file import

    When Place a dealer import file in the ftp.aiminspections.com/nissan/test2/,
    the nissan_dealer_load proxy will move the file from ftp.
    And a copy will be saved to the existing inspex folder on the s drive (S/dataload/AIM/(Inspex, InspexQA, InspexDEV)/Nissan_Dealer_Load_Code/IN).
    And go to CRM under search org page and search for dealer/org
    Then User should be able to see the file under that folder
    And User should be able to search and find dealer/org using dealer/org name from the import file




    Scenario: Test that Click scheduling appointments updates in CRM

    # Create request for home inspection in CRM and schedule an appointment and then update the task in Click Scheduler and see if the changes are updated in CRM 

    When create a Home request and then scheduled an appointment.
    And go to Click Scheduler and search for the task using Task Explore and enter the Request ID from CRM.
    And Task is found, double click on the task to open up 'request form'.
    And go to 'Assignment' tab and edit the 'Start' & 'Finish' time and click 'OK' to save the changes.
    And come back to CRM and check 'Appointment' section and click on the appointment to launch 'appointment audit' window and look at the latest update message received from Click and see if the assignment start and finish time has been updated
    Then in CRM the user should see the updated assignment/appointment start and finish time reflect accordingly in the latest message received from click.




    Scenario: Test the force created appointments in CRM are sent to Click properly

    Either create or use existing home request and schedule an appointment using 'Force Create' option to create appointment start and finish time and see if the appointment time shows up/updates in Click Scheduler

    "1. Create or use existing Home request.
    2. Then create an appointment using 'Force Create' option by choosing a appointment date and assign a start and finish time for the appointment.
    3. After that go to Click Scheduler and search for the task and see if the appointment date and start & finish time of the appointment displays accordingly."

    In Click, user should see the appointment date, appointment start and finsih time display accordingly.







    Scenario: Test that status updates in Click are sent to CRM

    # Change statuses of a Task in Click that have been assigned an appointment and check in CRM to see if the statuses are updating in appointment section of that request. 

    When Create or use existing Home request and schedule an appointment. 
    And in Click Scheduler, search for the Task and update the statuses.
    And Simutaneously check CRM againt the request to see if the statuses are updating accordingly  
    Then statuses should update accordingly in CRM.




    Scenario: Test that when appointments from imported dealer inspection requests are scheduled in Click and the times are updated in CRM

    # Create request for dealer inspection using import API in Postman and then update the task in Click Scheduler and see if the changes are updated in CRM 

    When Create a Dealer request using the import API, which should automatically create a click task.
    And go to Click Scheduler and search for the task using the Request ID.
    And Task is found, double click on the task to open up Task form.
    And Update appointment time
    Then Changes made in Click Seheduler should show up in CRM for the request




    Scenario: Pending home request job acts on requests it shouldn't. If you have a Manheim request with status ‘On hold’ and reason ‘pending home inspection’, The system should not return 500 error when there are no matching home requests..

    "When a dealer inspection request is imported and there is a matching (customer and accountNo) home inspection request and when the home request is scheduled at the time of the dealer import, set the status of the dealer request to 'On Hold' with reason Pending Home Inspection.

    E.g. Now is 6/5/17 4:00 am and we have a Nissan Home Request schedule for 6/5/17 8:30am with AccountNo 123987. A Nissan dealer import coming in at 4:01 am. The status of the dealer request is set to On Hold and the reason is Pending Home Inspection."

    When Schedule home request for now
    And Import dealer request with home request accountNo and customer.
    And Check to see if dealer import request is set to 'On-hold'.
    And  call the endpoint http://crm-api-qa.aiminspect.com/api/v1/inspection-requests/process-pending-home-inspection
    Then after calling the endpoint, the system should return successful.
    Home request is set to cancel.
    Dealer request status is changed to pending.
    




    Scenario: Pending home request job acts on requests it shouldn't. When calling the endpoint, it should call using the customer’s name.

    When Call the following endpoint http://crm-api-qa.aiminspect.com/api/v1/inspection-requests/process-pending-home-inspection
    And in the body, leave customer is blank. E.g (""customer"": "") and call the endpoint. 
    Then After calling the endpoint without the customer’s name, the system will return 422.




    Scenario: Click scheduler should not create a new task after canceling the original task when cancelling 'On-hold' home request 

    When Create a home request manually in CRM or search for a home request that is in 'P'otantial request status from advance search page and then schedule home request for now.
    And Import dealer request with home request accountNo and customer.
    And After that call the endpoint http://crm-api-qa.aiminspect.com/api/v1/inspection-requests/process-pending-home-inspection"

    Then The home request should be cancelled, and it's click task should be deleted and not re-created. Verify this in Click and in the appointment audit history. 
    And The dealer request should have an appointment created and sent to click





    Scenario: Click scheduler should not create a new task after canceling the original task when cancelling 'On-hold' home request 

    # When Create a home request manually in CRM or search for a home request that is in 'P'otantial request status from advance search page and then schedule home request for now.
    # And Import dealer request with home request accountNo and customer.
    # And After that call the endpoint http://crm-api-qa.aiminspect.com/api/v1/inspection-requests/process-pending-home-inspection"

    When The home request should be cancelled, and it's click task should be deleted and not re-created. Verify this in Click and in the appointment audit history. 
    Then The dealer request should have an appointment created and sent to click."





    Scenario: When a dealer request comes in and a home request is scheduled same day, set status appropriately

    "When a dealer inspection request is imported and there is a matching (customer and accountNo) home inspection request and when the home request is scheduled at the time of the dealer import, set the status of the dealer request to 'On Hold' with reason Pending Home Inspection.

    E.g. Now is 6/5/17 4:00 am and we have a Nissan Home Request schedule for 6/5/17 8:30am with AccountNo 123987. A Nissan dealer import coming in at 4:01 am. The status of the dealer request is set to On Hold and the reason is Pending Home Inspection."

    Given Schedule home request for now.
    When Import dealer request with home request accountNo and customer for now"

    Then After importing the dealer request, the dealer request in the ""On Hold"" status with ""Pending Home Inspection"" as the reason code.
    And The system should not schedule the dealer request to Click."







    Scenario: Process "On Hold - Awaiting Home Inspection" requests

    "When a dealer inspection request is imported and there is a matching (customer and accountNo) home inspection request and when the home request is scheduled at the time of the dealer import, set the status of the dealer request to 'On Hold' with reason Pending Home Inspection.

    E.g. Now is 6/5/17 4:00 am and we have a Nissan Home Request schedule for 6/5/17 8:30am with AccountNo 123987. A Nissan dealer import coming in at 4:01 am. The status of the dealer request is set to On Hold and the reason is Pending Home Inspection."

    When Schedule home request for now.
    And Import dealer request with home request accountNo and customer.
    And Using the app complete the home inspection.
    And Call the endpoint http://crm-api-qa.aiminspect.com/api/v1/inspection-requests/process-pending-home-inspection.
    Then After calling the endpoint, the system should put the status of the dealer request will be set to complete and the CR from the home request will be copied over.






    Scenario: Process "On Hold - Awaiting Home Inspection" requests

    "When a dealer inspection request is imported and there is a matching (customer and accountNo) home inspection request and when the home request is scheduled at the time of the dealer import, set the status of the dealer request to 'On Hold' with reason Pending Home Inspection.

    E.g. Now is 6/5/17 4:00 am and we have a Nissan Home Request schedule for 6/5/17 8:30am with AccountNo 123987. A Nissan dealer import coming in at 4:01 am. The status of the dealer request is set to On Hold and the reason is Pending Home Inspection."

    When Schedule home request for now.
    And Import dealer request with home request accountNo and customer.
    And Using the app, UTC the inspection and select Vehicle Purchased/Sold.
    And  Call the endpoint http://crm-api-qa.aiminspect.com/api/v1/inspection-requests/process-pending-home-inspection.
    Then After calling the endpoint, the system should put the status of the dealer request to scheduled for next available date.






    Scenario: UTC reschedule date shows on all UTCs, not just the proper one

    When Schedule an inspection for dealer request now (for current date).
    And UTC that appointment with an ""In body"" UTC, saying it won't be ready until two days later.
    And Check in CRM to see if the appointment has been rescheduled  new appointment for that day. 
    And UTC the new appointment again, but this time don't give it a date when it will be ready, just choose ""Weather""."
    Then In the appointment audit for the original UTC, it should show date that was selected using the app and the second appointment should not have a date.





    Scenario: Save inspection location on "Unable to Schedule"

    "1. Click on the schedule button
    2. update the address from XYZ to ABC 
    3. Select a date and click on 'check availability'
    4. Then click on 'unable to schedule' when the button is displayed.
    5. Then type in a comment in 'unable to schedule' field and then save the changes.
    6. Then go to back to request and try to schedule the appointment and look at the address being displayed.
    "

    The address that should be displayed is address ABC and not XYZ.




    Scenario: Modify some UTC actions to go to CSR queue

    "1. Schedule a dealer inspection request.
    2. Using the aim inspect app log in and UTC the inspection and select any of the following UTC option ('Vehicle Unavailable' with sub reason as 'cannot locate' or 'wrong location' as the reason)"

    Then user should see that the request status set to 'On Hold' awaiting csr when clicking on the status.





    Scenario: "CRM: Do not allow ""Pending Home"" to be chosen in UI

    When search for a request.
    And View the request and then change the request status to 'on hold' and try to select sub reason as 'pending home inspection'."
    Then User should not be allowed to select 'pending home inspection' as the subreason.




    Scenario: Add SMS to preferred contact methods

    When Go to add request page and select nissan dealer or manhiem as the customer.
    And in preferred method of contact, select SMS as the option to contact.
    And create the request and then view the request."
    Then User should see SMS as of the option for contact and also when viewing the request user should see SMS is displayed as the choice of contact.




    Scenario: Provide friendly error when user tries to create an appointment when one already exists

    When Open up chrome browser and log in to CRM and look up a request that is in 'P'ending satus.
    And open up another window in chrome and then log in to CRM and look up the same request that you were viewing on another browser. 
    And schedule an appointment for that request using any of the window that you're in. Make sure it's all scheduled.
    And come back to the window where the request has not been scheduled and now try scheduling an appointment."
    Then Upon trying to schedule an appointment, user should be promted with a friendly  error message  such as ""Oops an appointment is already scheduled by another associate. Please refresh the page to see the updates"" And when user refreshes the page, the user should see the request status change to 'S'cheduled and and appointment date and time should also display and the engineer the appointment has been assigned to."






    Scenario: "Modify organization import to not overwrite inspection location on update. 
    CASE 1: IF the organization that it is modifying has inspection location and location that are same (aka nobody has changed it), update all modified fields, and copy any location updates into inspection location.
    Then cascade all updates downstream, following existing logic for when to update requests' inspection location and appointments' locations, including Click."

    Search for an org that has location address and inspection location address to be the same. 

    "1. Create a NISSAN DEALER with an org that has location address and inspection locaiton address is same.  And use the locationCode of that dealer when sending the dealer import.
    2. Then send a modified org import for that organization and change the address to something other than the old address.
    3. Then view the request that was created with that organization and see if the location and inspection location was impected. 
    4. Also view the organization and see if the modified data is updated."

    "1. When viewing the request after the modified import comes for that organization. The request's inspection location and appointment location should be updated with the new address.
    2. And the organization in CRM should also be updated with new address in location and inspection location when viewing the org.
    3. And in request history a log should be recorded with ""Update from organization import""."




    Scenario: "Modify organization import to not overwrite inspection location on update. 
    CASE 2: If the organization that it's modifying has inspection location and location that are different (aka, manual updates were done to the inspection location), update all modified fields, but DO NOT copy any location updates into inspection location.
    Then cascade all updates downstream, EXCEPT THAT under no circumstances should the inspection location be updated on any request, nor should appointment locations be updated, nor should Click be updated."

    "1. Search for a organization in CRM and view the organization.
    2. Update the inspection location of the organization to something different. 
    3. Then create a Nissan Dealer request using that organization and schedule an appointment. 
    3. Then send a modified import for that organization and change the address to something other than the old address.
    4. Now view the request that was created with that organization and see if the location and inspection location was impected. 
    5. Also view the organization and see if the modified data is updated."

    "1. When viewing the request after the modified import comes for that organization. Request's appointment location nor inspection location should not be updated.   
    2. And the view the organization in CRM, the address change should reflect only on location of the organization and not the inspection location.
    3. And in request history a log should be recoed with ""Update from organization import""."






    Scenario: Appointment schedule on dealer requests allows you to submit invalid requests

    When Import dealer request
    And Navigate to it
    And Cancel existing appointment if needed
    And Click ""Schedule"" button
    And Click the save button in the dialogue
    Then user can't, because user never clicked "Check Availability" and selected a time




    Scenario: Advanced search should not allow server-killing queries

    When perform a basic search using Postman, for a query that will return a lot of results (e.g., '1'), with no limit query parameter
    And do the same for advance search except for an advanced search that will return a lot of results (e.g., country: 'US')
    And While that is running, use the CRM and verify that the server is still performing adequately
    Then the server should not crash when searching for data that is too large.





    Scenario: Force inspection address to be validated before check availability is clicked

    "{
    ""type"": ""NISSAN"",
    ""data"": ""C0000000201711099913N1CE2CP8FL364068   ALTIMA    15EDGARDO   BAEZ MANZANERA 4833 NW 116TH CT                                                      DORAL          AP3317878637014743052842201    01073BILL SEIDLE NISSAN, INC.                10500 NW 12TH ST                   MIAMI          FL331723056338000305635170720180703        FL           AIMIC""
    }"


    When Import a lease with an AP state
    And Click on ""Schedule"
    And DO NOT choose a state.
    And Select a date.
    And Click "Choose Availability"
    Then It validates the address and highlights invalid state.
    and 'check availability' button is disabled untill the state is entered. 






    Scenario: When importing dealer request, match to lease to populate lessee info

    When Import a dealer request with matching home request account number
    And also make sure that the dealer import has no lessee name and address 
    Then when viewing the request, in the lessee info section user should see lesssee info being displayed







    Scenario: When Click determines an address isn't valid, use 200 instead of 422 to communicate that to CRM

    When Enter in a valid address and click on 'check availability' and at the same time have network tab open
    And Check the network tab in the browser
    And Enter in an invalid address and click on check availability and at the same time check the network tab
    Then In the network tab, user should see 200 status ok instead of 422





    Scenario: Display loading spinner (basic, Advance search page)

    Given In basic search page
    When search for a request by entering '123' in the search box.
    And in advance search apge, filter the search and enter submit 
    Then spinner should display




    Scenario: UTC reschedule not working properly when SLA is in past

    SELECT id, sla_date FROM req.inspection_request WHERE sla_date < now()

    When Find requests with SLA date in the past in the DB.
    And go to CRM look up a request from the query and then schedule an appointment.
    And using the app log in to aim inspect and UTC the inspection and select (weather) as the reason and check the system when the inspection is rescheduled.
    Then the rescheduled date should be the start of the day tomorrow from the current date, and the due date should be the end of the day two days from the current date and the request's SLA date should be left as-is.





    Scenario: UTC reschedule date should show on the proper UTC and not all UTC's inspection.

    When Schedule an appointment on a request for (let's say) 6/1 UTC that appointment with an ""In body"" UTC, saying it won't be ready until 6/3
    And A new appointment will be created. UTC that one, but don't give it a date when it will be ready, just choose ""Weather""."
    Then User should see UTC earlist date the inspection can be done for the first UTC and not the second UTC when looking at the appointment audit





    Scenario: For home appointments, do not send dealer name to Click

    When Create a home request manually in CRM or import a home request.
    And schedule an inspection and make sure the inspection is schedule by refreshing the page.
    And make sure request status changed to 'S'cheduled from 'P'ending. 
    And  log in to click scheduler and search for the request and look up 'location' tab."
    Then Lessee's name should display as the locaiton name in location tab.





    Scenario: Do not create appointments during import of dealer requests that don't send to Click

    Remove a state or two from skyward_db - core.customer options column such as NJ, FL

    When Import a dealer request with a state that was removed from pre-condition column. 
    And Check crm and click scheduler if the system creates an appointment for the requerst"
    Then the system should not automatically create appointment for that request(s).






    Scenario: Previously inspected' UTC should cancel request and appointment

    When Import/ find a dealer request that has not been scheduled.
    And Scheduled it for today's date to show up in the app. 
    And Log in to the Aim inspect app and UTC the inspection and for reason select 'Previously inspected'.
    And Come back to CRM and search for the request and see what happens to it's request status and appointment. 
    Then the request be cancelled, in request history section there should be a log for the action and in the appointment section as well and Appointment will be complted w/UTC.




    Scenario: Force create at specific time, and actually force create

    When Create/find a request that has no appointment scheduled or a request that has an inspection scheduled.
    And Schedule an appointment for non scheduled request and or edit an appointment that has appointment schedule to a request.
    And Select a date from calender date picker and click on 'check availability'.
    And Force create button will dispaly when time and dates displayed, click on It.
    And enter in a time in the assigned time field and enter in date in any of required field and save your changes.
    And Come back to view request details page and refresh the page and look at the schedule appointment section. "
    Then The force create appointment time should display for the request and to make it working as it should, check click scheduler to make sure that the time slot is blocked for that request, and also this should create real Force create regardless of other inspections is scheduled for that time slot. "




    Scenario: Cancelling a request should also cancel  it's appointment.

    "1. Search for a request that has been scheduled already by going to advance search page and select 'scheduled' from status field.
    2. When search results are displayed, click on any of the request to view it.
    3. When in view request page, click on the 'S' status and 'Update status' window will pop up.
    4. Click 'C' in 'New status field and enter in a comment as it's a required field and click on save button to save your changes and see if the request and the appointment associated with the request gets cancelled. 
    "

    "1. The reuqest and it's appointment both should be cancelled. 
    2. The request status should change to 'C' and in the request histroy the action should show as ""Updated request status to Cancelled"" and who and what time the action was taken.
    3. And also in 'appointment' section the appointment status should also be updated to 'C' and wen drilling down to the appointment audit section the action should be '
    Click Message Received: ClickListener UPDATE; Task Status CANCELLED' and who and what time the action was taken should display."






    Scenario: Utc'ing  some dealer inspection should  put the request to 'on hold-Awaiting CSR' Status

    "1. Create and scheduled a dealer request for today to show up in the aim inspect app.
    2. Then log in to the app and UTC the inspection and use either utc reason(cannot locate, wrong location).
    3. Then come back to CRM and look for the reuqest by entering the request id in basic search page and when the result is displayed, click on it to view the request. "

    "1. When request is dislplayed after searching for it, hovering over the status should display 'On hold-awaiting csr action'.
    2. And when viewing the request user should see request status as 'H' and when clicking on the status icon 'H'. User should see current status as 'H'  on 'update status' window.
    Also user will see 'schedule' button and the appointment that was UTC'd will show 'C/utc'.
    and a log of UTC will be stored in request history page."





    Scenario: Completing an inspection where the vin is lower case should not cause any issue updating it coresponding request

    When Create a dealer or home request for Nissan with a lower-case VIN.
    And Do an inspection and complete it.
    And Come to CRM and search for that request.
    Then It updates this vehicle with CR link, and completes request and it should change the request status as 'C'omplete and re-inspection option be displayed.
   




    Scenario: When Click determines address isn't valid, still get availability

    "1. Find a reuest that has not been scheduled.
    2.Click on 'schedule' button to schedule an inspection.
    3. When the appointment section pop up box opens up then enter in an invlid address such as (99910 11 Mile Road, Farmington Hills, MI 
    48331)."

    "Check availability' button should be enabled even if the address is inavalid and let user schedule an inspection as the address actually may be lagit.
    And display date and time.
    And a message will display as follows ""Invalid Address. Please enter a valid address above and try again."""




    Scenario: Able to search for single/multiple vins in advance search page

    When Log on to CRM and go to 'Advance' search page
    And In vin field, enter in single or multiple vins and click on search
    Then The search shoud return results that match exactly, e.g. abcd1234 will match ABCD1234, but not ABCD12345 and the search should be case insensitive






    Scenario: When inspection is UTC'd and the appointmet status is at "Dispatched/Acknowledged/etc" then move the request to complete

    When Create/import a dealer request.
    And Schedule an inspection for today and make sure it gets scheduled through click.
    And  go to Click scheduler and search for the reuest and view the request and go to 'general' tab and see the status, which is 'scheduled'.
    And Change the status to ""Dispatched/Acknowledged/etc"" and save the changes.
    And  log in to Aim inspect app and UTC the inspection and select reason as 'wrong location'.
    And Come back to CRM and search for the request that was UTC'd"
    Then system completed the inspection with UTC reason and sub-reason displayed, and request status was changed to On Hold awaiting CSR, and then went back to click and did not find that task/assignment after searching for it."





    Scenario: Restrict "callcenter" from creating dealer request

    When Log on to CRM using username/password as 'callcenrter/crmiscool'.
    And Go to 'Request' link and click on 'add request'.
    And For customer select 'Nissan' and for requrest type see if 'dealer' is displayed"
    Then Dealer as the request type option should not be displayed.




    Scenario: Restrict "callcenter" from searching for dealer request (Basic search tab)

    When Log on to CRM.
    And In basic search BOX enter iN ""123" and click on search.
    And  When results are displayed, sort by request type and see if 'dealer' requests are displayed. vin field, enter in single or multiple vins and click on search
    Then Dealer requests shouldn't be displayed. 




    Scenario: Restrict "callcenter" from searching for dealer request (advance serch tab)

    When Log on to CRM using username/password as 'callcenrter/crmiscool'.
    And Go to advance search tab and from request type dropdown field see if 'dealer' is displayed.
    Then Dealer' option shouldn't be displayed.




    Scenario: Restrict "callcenter" from viewing for dealer request

    When Log on to CRM using sample/crmpasswordgoeshere as the user name and password.
    And Search for a dealer request and when results are displayed, write down any dealer request ID.
    And Log out and log back in using callcenter/crmiscool account.
    And in basic search page, enter in the dealer request ID and see if the result is displayed
    Then the result shouldn't display.




    Scenario: Callcenter user should not be allowed to choose preferred contact method 

    When Log on to CRM using callcenter/crmiscool and create home request
    And in add request page, check to see if you are able to choose preferred contact method
    Then User should not be able to select/choose preferred contact method





    Scenario: Callcenter user should not be allowed to see preferred contact method (basic search page)

    When Log on to CRM using callcenter/crmiscool.
    And in basic search page, enter in '123' and click on search button.
    Then Callcenter user should only see home request in the search results and when viewing the request callcenter user shouldn't be able see preferred contact method as the user is unable to edit request. Also home requet shouldn't have preferred contact method option to begin with






    Scenario: Cancelling an appointment should change the request status to 'P'ending

    When Log on to CRM and search for scheduled requests and when results shows up, view a request.
    And cancel the appointment.
    Then Upon cancelling the appointment, the request status should be changed to Pending and in the appointment audit log section should log the chagen accordingly and in the request history audit table the log should be recorded as well.





    Scenario: Lower case vins should be decoded

    When Log on to CRM 
    And go to add request page
    And Enter in a vin in lower case
    Then the system should decode the year, make, model and trim of the vehicle





    Scenario: Show friendly message when ESB times out for get availability

    When Log on to CRM and launch schedule appointment section or edit an appointment.
    And disconnect from internet/wifi and click on 'check availability'
    Then If and when ESB times out, user should see the following friendly message "We are experiencing problems with checking availabilities. Please try again later."




    Scenario: Request status updates should be driven by Click-Enabled customer (Pending)

    When Log on to CRM and search for requests that is in 'P'ending status.
    And Click on a request from the list to view it.
    And click on request status 'P' icon to launch 'update status' window.
    And In 'Update Status' window see if 'pending' option can be selected.
    Then Clicking on 'pending' option shouldn't trigger anything in the UI.
    




    Scenario: Request status updates should be driven by Click-Enabled customer (Cancelled)

    When Log on to CRM and search for requests that are not in either completed or cancelled status.
    And Click on a request from the list to view it.
    And click on request status icon to launch 'update status' window.
    And In 'Update Status' window click on 'C'ancel option in new status field. "
    Then User should be able to cencel the request by changing the current status to 'C'ancelled.
   





    Scenario: Request status updates should be driven by Click-Enabled customer (Complete)

    When Log on to CRM and search for requests that is in 'C'omplte status.
    And Click on a request from the list to view it.
    And Then click on request status icon to launch 'update status' window.
    And In 'Update Status' window see if 'C'omplete option is clickable and selectable."
    Then User shouldn't see anything else but 'C'omplete as the status and there should be no new status option, and clicking on the 'save' button shouldn't cause any error and able to close the window after ward."






    Scenario: Request status updates should be driven by Click-Enabled customer (Potential)

    "1. Log on to CRM and search for requests that is not in 'P'otential status.
    2. Click on a request from the list to view it.
    3. Then click on request status icon to launch 'update status' window.
    4. In 'Update Status' window see if 'Potential' option can be selected."

    "1. 'Potential' option as the new status should not be available.
    2. User can only select 'C' and or 'H' as theose are the options given.
    3. User should not be allowed to click/choose 'Potential' option directly from UI."







    Scenario: Request status updates should be driven by Click-Enabled customer (On Hold)

    "1. Log on to CRM and search for requests that is not in on 'H'old status.
    2. Click on a request from the list to view it.
    3. Then click on request status icon to launch 'update status' window.
    4. In 'Update Status' window see if on 'H' option can be selected."

    "1. User should be able to select on 'H'old as the new status and select a reason for putting the request on hold. By default the reason should be 'Awaiting Dispatch"" but user can set it anything from the dropdown list.
    2. And in request history audit section, there should be a log to reflect the changes.
    2. And any active appointment should get cancelled and also in appointment audit section. There should be a click message to show the appointment is cancelled."





    Scenario: Request status updates should be driven by Click-Enabled customer (On Hold)

    "1. Log on to CRM and search for requests that is in (on 'H'old) status.
    2. Click on a request from the list to view it.
    3. Then click on request status icon to launch 'update status' window.
    4. In 'Update Status' window see if (on 'H'old) option can be selected."

    "1. User should be able to select on 'H'old as the new status and select a reason for putting the request on hold. By default the reason should be 'Awaiting Dispatch"" but user can set it anything from the dropdown list.
    2. And in request history audit section, there should be a log to reflect the changes.
    2. And any active appointment should get cancelled and also in appointment audit section. There should be a click message to show the appointment is cancelled."




    Scenario: Request status updates should be driven by Click-Enabled customer (Data Review)

    "1. Log on to CRM and search for requests that is not in on 'Data Review' status.
    2. Click on a request from the list to view it.
    3. Then click on request status icon to launch 'update status' window.
    4. In 'Update Status' window see if 'Data Review' option can be selected."

    "1. 'Data Review' option should not be available.
    2. User can only select 'C' and or 'H' as theose are the options given.
    3. User should not be allowed to click/choose 'Data Review' option directly from UI."






    Scenario: Request status updates should be driven by Click-Enabled customer (Scheduled)

    "1. Log on to CRM and search for requests that is not in on 'Scheduled' status.
    2. Click on a request from the list to view it.
    3. Then click on request status icon to launch 'update status' window.
    4. In 'Update Status' window see if 'Scheduled' option can be selected."

    "1. 'Scheduled' option should not be available.
    2. User can only select 'C' and or 'H' as theose are the options given.
    3. User should not be allowed to click/choose 'Scheduled' option directly from UI."







    Scenario: Request status updates should be driven by Click-Enabled customer (ATL Review)

    "1. Log on to CRM and search for requests that is not in on 'ATL Review' status.
    2. Click on a request from the list to view it.
    3. Then click on request status icon to launch 'update status' window.
    4. In 'Update Status' window see if 'ATL Review' option can be selected."

    "1. 'ATL Review' option should not be available.
    2. User can only select 'C' and or 'H' as theose are the options given.
    3. User should not be allowed to click/choose 'ATL Review' option directly from UI."







    Scenario: Comment is required when cancelling appointment

    "1. log on to CRM and search for any active appointments.
    2. View the request from the search result list.
    3. Then cancel the appointment by clicking on the thre dotted line in the 'current appointment details' window.
    4. 'Cancel appointment' pop box will dispaly, select a reason from the drop down and enter in a comment and click on 'Done' to save your changes"

    "1. The system should cancel the appointment.
    2. The appointment status should display as 'C' in red background.
    3. And the comment should display in 'Appointment' section as message form and when hover over it user should see the comment. "







    Scenario: Cancel an appointment without entering comment

    "1. log on to CRM and search for any active appointments.
    2. View the request from the search result list.
    3. Then cancel the appointment by clicking on the thre dotted line in the 'current appointment details' window.
    4. 'Cancel appointment' pop box will dispaly, select a reason from the drop down and don't enter in a comment and see if 'Done' button is displayed."

    "1. The 'Confirm' button should not be displayed.
    2. Only thing user can do is click on cancel button to exit from the pop up box, or click on 'x' on the right side of the box to close the window.
    3. And doing so shouldn't trigger any cancellation of the appointment.  "




    Scenario: Appointment should be able to be UTCed in any status even when the appointment is as dispatched or even far along in the process

    "1. log on to CRM and schedule an inspection for today to show up in the aim inspect app and assign it to an engineer.
    2. Refresh the page to make sure the request status and appointment status is updated accordingly.
    3. Go to click and search for the request and when found update the appointment status to acknowledged and then again to dispatched and save your changes.
    4. Then log on to the app and UTC the inspection.
    5. Come back to CRM again and search for the request and see if the request is completed and marked UTC'd "

    "1. Depanding on the UTC reason and the action associated with it should update the request status accordingly.
    2. Also based on the Action take the appointment status should be updated accordingly.
    3. To see the list of reason and it's action see https://confluence.aiminspections.com/pages/viewpage.action?pageId=3180257"





    Scenario: Create timed job to call V2 modified endpoint at 11:30 PM Eastern

    "1. Modify several requests for current date in which ever env you want to run the test against.  And note the reuqest ID
    2. Then call the GET request route /api/v2/inspection-request/modified. 
    3. The query parameters should be the customer, e.g. customer=NISSAN, and the modified date, e.g. modifiedDate=06-08-2017.
    4. Then go to S3 bucket in AWS and search for req-status-(env).
    5. Filter the last modified column and see if a file for the date you trigger the get request route shows up."

    "1. A JSON file should generate for the modifed date.
    2. Click on it to download it.
    3. After download is complete then open it up with text editor file.
    3. Then search for the requests that you have modified, and those request should be found on the json file."




    Scenario: Audit reason text along with reason ID

    "1. log on to CRM and search for a request that has been scheduled.
    2. Then cancel the request "

    In the request history section, the request status should show 'cancel' with reason ID= 2 and reason as 'per aim request'




    Scenario: Audit reason text along with reason ID

    "1. log on to CRM and search for a request that has been scheduled.
    2. Then cancel the appointment by clicking on the three dotted icon in 'current appointment details' window.
    3. And select a reason from the dropdown and enter in a comment and click on 'done' button to save you changes and then look at the appointment audit table."

    "1. The appointment status should change to 'c'ancel.
    2. The request status should change to 'p'ending.
    3. In the appointment audit section, the reson text should show reflect the resoon chosen when appointment was cancelled and the reason ID and comment that was made and status of the appointment and date to reflect when was the action taken. "




    Scenario: Get availability doesn't show in the new system with a address that works with lagecy system

    The system should display date and time slot for inspection location. 




    Scenario: Log response from server on successful re-send

    "To fake a resent click message, you can insert a row into the req.click_queue table, with a click message to send. So the way to do this is:
    1. Find a request in CRM that has been scheduled.
    Copy the calliD:apptID of the appiontment found in appointment audit section within click task action message.
    2. Now run an insert query as follows: ""insert into req.click_queue
    (message, status, appt_id)
    values ('<SXPTaskOperations Revision=""7.5.0""> 
    <Task> 
        <CallID>343533:23178</CallID> 
        <Number>0</Number> 
        <Status>Cancelled</Status> 
    </Task> 
    </SXPTaskOperations> ', 1, 23178)""
    3. After getting a successful insert, look at the table the insert was sent. you will see a new row is created.
    4. now using postman, send a post to ""{{requestProcessorUrl}}/api/v1/click-queue""
    5. Go back to req.click_queue table and see that the status column change from 1 to 2. 
    6. And also check the request in CRM and see if click resend message is displayed in CRM"

    The click resend message should be displayed in appointment audit setion. 




    Scenario: Allow "management" role to change Completed requests back to Pending

    "1. Log in to CRM using management/crmisnice user.
    2. Search for click enabled request that has been completed.
    3. View the request and click on the completed requet and status window will pop up. You will see 'P'ending as the option, click on it to change the status of the request."

    "1. After changing the request status, the request status should change to 'P'ending.
    2. And user should see 'schedule' button displayed under calendar icon."




    Scenario: Cancelling appointments when going to "On Hold" should only happen for Click-enabled appointments

    "1. Find or create a Nissan request with an appointment.
    2. Change the request status to ""On Hold"""

    "The request status is On-Hold and the appointment is cancelled.
    NOTE THAT THE CANCELLATION LOGIC SHOULD REMAIN IN PLACE FOR CLICK ACCOUNTS, so please also test with Nissan and ensure that the appointment is cancelled in that scenario."




    Scenario: Home requests, and lessees in general, should not "fall back" to dealer phone number

    "1. log on to CRM and create a home request and enter in primary and business numbers and make sure that both are different.
    2. When in view request details page, look at the phone number, it will display the lessee primary home number only. And if primary was missing then business phone number would show.
    3. Now update the request by going to db and run the following query (UPDATE req.inspection_request SET phone_numbers = '[{""tags"": [""home"", ""primary"", ""mobile"", ""work""], ""number"": ""3478885858""}, {""tags"": [""dealer""], ""number"": ""5867775777""}]'
    WHERE id = 'request ID goes here' and see if dealer phone number shows up on the home request"

    "1. The dealer phone number should not show up.
    2. Also check click scheduler for that request and check throuh the request to see if dealer number is displayed as It shouldn't."





    Scenario: Modify the scheduled endpoint to use a different time window

    When Log on to CRM and see if there are any inspections assigned to the engineer you're associated with in within - 8 hours from current time and also if there is anything assigned for current date.
    And If so, then log in to Aim inspect app and see if inspections from the past and current inspection shows up in the app. 
    Then Those inspections should show up in the app.




    Scenario: "On Hold" logic for same-day dealer requests must work even if the appointment is dispatched

    "1. Create a Nissan home request for now.
    2. Schedule an appointment for it.
    3. Move that appointment to ""Dispatched"" status by going to click and search for the request and under general tab select 'dispatched' as the appointment status. 
    4. Import a dealer request with the same Account#."

    "1. The dealer request should be put on It's put into ""On Hold - Pending Home"" status.
    NOTE: When fixing/testing this, it is okay for it to cancel things in an ""Acknowledged"" or later status for future days, since that should never happen in real production."




    Scenario: Dealer request should populate with lease data whenever it exists (pending)

    When Create/use existing a home request
    And Import a dealer request with matching home account number
    And Check CRM and Click scheduler and verify if lessee info is displaying
    Then Lessee's info should display for dealer request that matches the account number in CRM and as well as in Click scheduler





    Scenario: Dealer request should populate with lease data whenever it exists (Scheduled)

    When Create a home request
    And Schedule an inspection
    And Import a dealer request with matching home account number.
    And Check CRM and Click scheduler and verify if lessee info is displaying
    Then Lessee's info should display for dealer request that matches the account number in CRM and as well as in Click scheduler





    Scenario: Dealer request should populate with lease data whenever it exists (Acknowledged)

    When Create a home request.
    And Scheduled an inspection then go to Click and chencge the status of the appointment to Acknowledged.
    And Import a dealer request with matching home account number.
    And Check CRM and Click scheduler and verify if lessee info is displaying.
    Then Lessee's info should display for dealer request that matches the account number in CRM and as well as in Click scheduler.




    Scenario: Dealer request should populate with lease data whenever it exists (Dispatched)

    When Create a home request
    And Scheduled an inspection then go to Click and change the status of the appointment to Dispatched
    And Import a dealer request with matching home account number.
    And Check CRM and Click scheduler and verify if lessee info is displaying
    Then Lessee's info should display for dealer request that matches the account number in CRM and as well as in Click scheduler




    Scenario: Dealer request should populate with lease data whenever it exists (on site)

    When Create a home request
    And Scheduled an inspection then go to Click and change the status of the appointment to 'on site'
    And Import a dealer request with matching home account number.
    And Check CRM and Click scheduler and verify if lessee info is displaying
    Then Lessee's info should display for dealer request that matches the account number in CRM and as well as in Click scheduler




    Scenario: Only update requests and organizations with new address when they differ

    "1. Search for an org in CRM that has location and inspection location are the same for the organization. 
    2. Create a dealer request with that org and schedule it. 
    3. Import the organization, but don't change any of the data in the import. 
    4. Before re-sending the import again change the name of the organization for the import (the second, longer name: https://confluence.aiminspections.com/display/SKYW/Nissan+Dealer+File+Import) and re-import it again. 
    5. Next, change the inspection location of the organization in CRM and then re-run the organization import. "

    "1. The organization, dealer request location and the request's appointment should not be updated. 
    2. The request and appointment dealer name should be updated, and the existing click task dealer name should be updated. The click task should not be deleted and recreated."




    Scenario: Exclude holidays when calculating SLA

    Need to set holiday date(s) in core.sla_date table prior to import. For example if you're importing a dealer req for today (07-28-2017) and the sla date is set to 2 days from today which is 08-01-2017. So if you set holiday as 08-01-2017 then sla date should be 08-02-2017

    When Import a dealer request
    And After import is successful go to click and see what's the SLA date
    Then Check req.inspection_request-sla_date column against the request and the sla date should be two days after the import date excluding the holiday




    Scenario: Inspection location on organization does not behave properly with dealer requests

    Create an organization that has a different location and inspection location

    When Import a dealer request for Nissan for that organization
    And In the body of JSON, enter in a completely different address than the billing address or inspection location of the org
    Then it creates an appointment to the address of the inspection location of the orginazation






    Scenario: Lease load should only update pending/potential status records

    Request needs to be on either potential/pending status

    When Search for a request that is in 'potential/pending' status 
    And Select a request and note down the account number and vin
    And  setup the request data and in the json body modify some data and then insert the account number and vin that was noted and send an update request to /api/v1/lease/import
    Then the request data is updated





    Scenario: Lease load should only update pending/potential status records

    Request needs to be on 'On-hold' status

    When Search for a request that is in 'On-hold' status. 
    And Select a requerst and note down the account number and vin
    And setup the request's data and in the json body modify some data and then insert the account number and vin from above step and send an update request to /api/v1/lease/import
    Then the request data is not updated




    Scenario: Create request exporter for cancels for Toyota (Pending status)

    "1. Create TFS request using postman and send it to {{requestImporterUrl}}/api/v1/inspection-request/import/tfs/soap and note down the external ID.
    2. Then export the request to request processor.
    3. Check CRM and see if the request exist and it should.
    4. Then paste the external ID in the json body and send a cancel route to {{requestImporterUrl}}/api/v1/inspection-request/import/tfs/soap.
    5. Then re-run the export endpoint."

    "The system should respond back with a 200 OK status.
    Also in the response json body user should see the following ""<s:Envelope xmlns:s=""http://schemas.xmlsoap.org/soap/envelope/"">
        <s:Body>
            <CancelInspectionResponse xmlns=""http://tempuri.org/"">
                <CancelInspectionResult>24676</CancelInspectionResult>
            </CancelInspectionResponse>
        </s:Body>
    </s:Envelope>"".
    The request should show canelled in CRM."



    Scenario: Create request exporter for cancels for Toyota (Scheduled/On-hold status)

    "1. Create TFS request using postman and send it to {{requestImporterUrl}}/api/v1/inspection-request/import/tfs/soap and note down the external ID.
    2. Then export the request to request processor.
    3. Check CRM and see if the request exist and it should.
    4. Schedule an inspection.
    5. Then paste the external ID in the json body from when the request was created and send a cancel route to {{requestImporterUrl}}/api/v1/inspection-request/import/tfs/soap.
    6. Then re-run the export endpoint."

    "The system should respond back with a 200 OK status.
    Also in the response json body user should see the following ""<s:Envelope xmlns:s=""http://schemas.xmlsoap.org/soap/envelope/"">
        <s:Body>
            <CancelInspectionResponse xmlns=""http://tempuri.org/"">
                <CancelInspectionResult>24676</CancelInspectionResult>
            </CancelInspectionResponse>
        </s:Body>
    </s:Envelope>"".
    The request should show cancelled in CRM."



    Scenario: Create request exporter for cancels for Toyota (On-hold status)

    "1. Create TFS request using postman and send it to {{requestImporterUrl}}/api/v1/inspection-request/import/tfs/soap and note down the external ID.
    2. Then export the request to request processor.
    3. Check CRM and see if the request exist and it should.
    4. Put the request on 'On-hold'.
    5. Then paste the external ID in the json body from when the request was created and send a cancel route to {{requestImporterUrl}}/api/v1/inspection-request/import/tfs/soap.
    6. Then re-run the export endpoint."

    "The system should respond back with a 200 OK status.
    Also in the response json body user should see the following ""<s:Envelope xmlns:s=""http://schemas.xmlsoap.org/soap/envelope/"">
        <s:Body>
            <CancelInspectionResponse xmlns=""http://tempuri.org/"">
                <CancelInspectionResult>24676</CancelInspectionResult>
            </CancelInspectionResponse>
        </s:Body>
    </s:Envelope>"".
    The request should show cancelled in CRM."






    Scenario: Create request exporter for cancels for Toyota (Complete/On-hold status)

    "1. Create TFS request using postman and send it to {{requestImporterUrl}}/api/v1/inspection-request/import/tfs/soap and note down the external ID.
    2. Then export the request to request processor.
    3. Check CRM and see if the request exist and it should.
    4. Schedule an inspection.
    5. Complete the inspection.
    6. Then paste the external ID in the json body from when the request was created and send a cancel route to {{requestImporterUrl}}/api/v1/inspection-request/import/tfs/soap.
    7. Then re-run the export endpoint."

    "The system should respond back with a 200 OK status.
    Also in the response json body user should see the following ""<s:Envelope xmlns:s=""http://schemas.xmlsoap.org/soap/envelope/"">
        <s:Body>
            <CancelInspectionResponse xmlns=""http://tempuri.org/"">
                <CancelInspectionResult>24676</CancelInspectionResult>
            </CancelInspectionResponse>
        </s:Body>
    </s:Envelope>"".
    The request should not be cancelled in CRM since the request is completed."

