# http://stackoverflow.com/questions/25649848/running-cucumber-tests-on-different-environments
# FOR BASE_URL_PROD
# NOTE:
# You're probably using tab characters to indent your YAML file.
# This is not permitted by the YAML spec:
# To maintain portability, tab characters must not be used in indentation, since different systems treat tabs differently.
#Note that most modern editors may be configured so that pressing the tab key results in the insertion of an appropriate number of spaces.
###
# ALSO MAKE SURE all /config/...yml files contain the same test environments.

---
qa:
    :url: https://www.autodesk.com

staging:
    :url: https://www.autodesk.com

prod:
    :url: https://www.autodesk.com

sle:
    :url: https://www.autodesk.com